### PR TITLE
Use Svelte v3

### PR DESCRIPTION
**Pull request by sisou**
I updated the packages and changed the file extension to `.svelte`.

I added the `resolve()` plugin so that the build includes the required `svelte/internal` helpers so the built component is able to run stand-alone. I think this is the expected behavior of this template?

### CODE REVIEW

**Comment by EmilTholin** [comment]
I think you might want to use `resolve` just for the `umd` build, and set `svelte/internal` as an external dependency for the `es` build, but I'm not entirely sure.

E.g:
```javascript
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import pkg from './package.json';

const input = pkg.svelte;
const name = pkg.name
  .replace(/^(@\S+\/)?(svelte-)?(\S+)/, '$3')
  .replace(/^\w/, m => m.toUpperCase())
  .replace(/-\w/g, m => m[1].toUpperCase());

export default [
  {
    input,
    output: { file: pkg.main, format: 'umd', name },
    plugins: [
      svelte(),
      resolve()
    ]
  },
  {
    input,
    output: { file: pkg.module, format: 'es' },
    external: ['svelte/internal'],
    plugins: [svelte()]
  }
];
```

**Comment by wayne-o** [comment]
This works for the most part but it seems to be ignoring content in `<style>`  - has anyone else seen this?

**Comment by sisou** [comment]
I have tried it with

```html
<script>
    export let name;
</script>

<h1>Hello {name}!</h1>

<style>
    h1 {
        color: rebeccapurple;
    }
</style>
```
and the CSS is included in the built files ( `index.js` and `index.mjs`).

**Comment by YogliB** [comment]
Is this PR under review?

**Comment by sisou** [comment]
I think we have to ping @rich_harris, but I also remember him saying in the Discord once that he has bigger plans for this repo than just a simple v3 update. He mentioned adding test infrastructure, IIRC.

But maybe this PR should still be merged until he finds time for that?

**Comment by sisou** [comment]
I think we have to ping @Rich-Harris, but I also remember him saying in Discord once that he has bigger plans for this repo than just a simple v3 update. He mentioned adding test infrastructure, IIRC.

But maybe this PR should still be merged until he finds time for that?

**Comment by YogliB** [comment]
@sisou

In the meantime, I've made a [template](https://github.com/YogliB/svelte-component-template) based on the app and component templates.

It's Svelte 3 based, but other than that it works exactly the same **and** you can preview your component running `npm run dev`, just as you would do in a full-blown app.

**Comment by wayne-o** [comment]
@yogev I haven’t tried this yet but it looks awesome - thank you for this

**Comment by Conduitry** [comment]
Sorry this sat for so long! I think there are still vague bigger plans for this repo, but this is definitely much better than the v2-only thing this template was before.

**Comment by antony** [comment]
In case it's useful - I adapted the original repo to include livereload, making component development significantly easier.

https://github.com/antony/svelte-component-seed

**Pull request merged**
